### ISSUE TITLE
Support s3 driver

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#11]
Preferably by direct HTTP implementation

**Comment by danielroe** [comment]
> Preferably by direct HTTP implementation
@pi0 You mean using the REST API as opposed to an SDK, right?

**Comment by pi0** [comment]
Yes!

**Comment by dsfx3d** [comment]
is S3 support still under consideration?

**Comment by dsfx3d** [comment]
@pi0 why do you prefer HTTP implementation over SDK?

**Comment by qin-guan** [comment]
Would the team be open to considering a DynamoDB driver as well?

**Comment by amandesai01** [comment]
is this open for PR? I am willing to contribute.

**Comment by amandesai01** [comment]
@dsfx3d HTTP implementation because we want this to run on lambda/edge functions. SDK creates a long lived connection which is not preffered in our case.

**Comment by becem-gharbi** [comment]
I don't know if anyone is working on an S3 driver. I have tried [aws4fetch](https://github.com/mhart/aws4fetch) for signing HTTP requests and it works well. I have built a [nuxt module](https://github.com/becem-gharbi/nuxt-s3-edge) based on it. You can find the Unstorage driver [here](https://github.com/becem-gharbi/nuxt-s3-edge/blob/main/src/runtime/server/plugins/storage.ts).

**Comment by pi0** [comment]
Landed in #361
