### ISSUE TITLE
Support native ttl

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#13]

**Comment by tiborpino** [comment]
@pi0 Any progress here?

**Comment by McPizzaIs** [comment]
for Redis, this could be addressed by #150

**Comment by pi0** [comment]
Thinking more about the generic TTL idea, the new transaction options feature (https://github.com/unjs/unstorage/pull/168) can allow any driver to implement it per `setItem` call in their native way.


Also drivers can globally support ttl. For memory, you can use [LRU Driver](https://unstorage.unjs.io/drivers/lru-cache) instead with [ttl option](https://www.npmjs.com/package/lru-cache#ttl).
