### ISSUE TITLE
return the created time from meta

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/unstorage#136]
### Describe the feature

In this file, https://github.com/unjs/unstorage/blob/main/src/drivers/fs.ts#L46, only the accessed and modified time are returned but I think the created time could be very useful (in particular for Nuxt Content and Docus) 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Added new `ctime` and `birthtime` (you might need to use birthtime as creation time. ctime is last status change)

**Comment by Barbapapazes** [comment]
Thanks!
