### ISSUE TITLE
Incrementing / Decrementing Values Support

### ISSUE THREAD

**Issue by harlan-zw** [unjs/unstorage#152]
### Describe the feature

This is a common pattern in Laravel for [Cache](https://laravel.com/docs/9.x/cache#incrementing-decrementing-values) and the [Database](https://laravel.com/docs/9.x/queries#increment-and-decrement).

Would be awesome to see it also supported, would be happy to help with a PR.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We could support such API in entity layer (https://github.com/unjs/unstorage/issues/25)

**Comment by harlan-zw** [comment]
> We could support such API in entity layer (#25) on top of storage.

Interesting, is the idea that the entity layer would be abstract or that it should be specific for the driver?

**Comment by pi0** [comment]
Yes (a new package getting public soon).

**Comment by TimoGlastra** [comment]
Hey! I'm curious on the status of this new package. I'm currently in need of a solution where I can increment a counter (that is not prone to race condition errors).  

Is there already a native solution, or should I build a custom thing for now?

**Comment by pi0** [comment]
Hi. I have reopened because more thinking might make sense to support atomic operations with leveraging driver natives. Still not sure the best way to avoid (mainly bundle) overheads but let's track it again 👍🏼

**Comment by pi0** [comment]
I think it is a non-goal or at least not something easily to implement being both agnostic and fast.
