### ISSUE TITLE
Storate throws an error when try to put circular object

### ISSUE THREAD

**Issue by alex-key** [unjs/unstorage#165]
### Environment

- `@unjs/storeage`: `v1.1.5`
- `node`: `v16.18.1`

### Reproduction

```
const storage = createStorage({
  driver: localStorage({ base: "app:" }), // could be any driver
});

// create a circular object
const a = { b: {} };
a.b.parent = a;

storage.setItem('item-a', a) // throws an error
```

### Describe the bug

`storage.setItem` is failing (for any driver), when trying to save a circular object. It happens because to serialize objects and arrays `storage.ts` uses `JSON.stringify`. The solution would be to use some transform function which could prepare object: re-format circular dependencies and make object safe to be processed by `JSON.stringify`.

### Additional context

I found this issue, while debugging another one reported in https://github.com/unjs/nitro/issues/957. So basically nitro uses `unstorage` to cache some request/response and fails, because of nested property `socket` which is an object of class `Socket`, and it has a reference to a parent. Circular reference seems to be a very common case for HTTP res/req objects.

### Logs

```sh
Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'b' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (_utils.ts:43:17)
    at Object.setItem (storage.ts:141:52)
```

**Comment by alex-key** [comment]
I am working on this, so you could assign to me. Just created this issue to track progress.

**Comment by alex-key** [comment]
@pi0 @danielroe Prior to implement a fix, I want to have your opinion on the following topic.
I planned just use some good `decycle`/`restoreCycle` algorythm and process any object provided to `setItem` before stringify.
Mozilla docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value#see_also) is referring to the [cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js). It works good, but it uses `eval()` on restore circular to assign referenced objects like this
```
var path = item.$ref;
if (typeof path === "string" && px.test(path)) {
  value[name] = eval(path);
}
```
There is also other available implementations like [ungap/structured-clone](https://github.com/ungap/structured-clone) or [flatted](https://github.com/WebReflection/flatted), but I think that all of them will lead to worse performance. Additionally `structured-clone` cannot be used as is, because it changes the structure of plain simple objects when saved to storage. So it would break existing storages of the users.

So ideally we want to decycle only circular objects and just use simple `JSON.stringify()/destr()` for regular objects (cycle-free). But from my perspective detecting `isCurcular` w/o using a simple `try { return JSON.stringify(value) } catch(err) {  return JSON.stringify(decycle(value)) }` could be another performance issue.

I'm wondering based on your experience maybe you know the best possible way to detect and decycle/restoreCycle for circular objects. And what is your opinion on using `eval()` in the referenced solution and `try-catch` to detect circular. Otherwise I could continue investigation and try to do some performance tests and find the best possible algorythm.
Thank you!

**Comment by pi0** [comment]
Hi dear @alex-key. I think it is good idea to support nested objects with cycling values only it is probably too much effort to put it in low level core. You might do it by your self to serialize/deserilize values before passing to `getItem` and `setItem`. We might support data interceptors (https://github.com/unjs/unstorage/issues/23) or a simple function to replace default serializer too.

**Comment by pi0** [comment]
BTW i would recommend checking out [devalue](https://github.com/Rich-Harris/devalue) it has a good support for edge cases and serializing types.

**Comment by alex-key** [comment]
@pi0 I see. Please, check related issue in `nitro` (https://github.com/unjs/nitro/issues/957) and maybe you want to left a comment and close it as well.
