### ISSUE TITLE
Published package does not contains `.cjs` files

### ISSUE THREAD

**Issue by farnabaz** [unjs/unstorage#17]
Latest release of `unstorage` does not contains `.cjs` files and it `unbuild` still generates `.js` files

Seems that its related to unbuild and there is an unpublished fix for this issue https://github.com/unjs/unbuild/commit/a1c8c0fb9d93dad57e876e3876e91854cb321612

Also I thinks we should define `ext` option for drivers in `build.config`

```
    { input: 'src/drivers/', outDir: 'drivers', format: 'cjs', ext: 'cjs', declaration: false }
```

**Comment by pi0** [comment]
Thanks for reporting issue. For now using back `.js` till releasing unbuild :)
