### ISSUE TITLE
Redis driver requires either a host, url or cluster option

### ISSUE THREAD

**Issue by minkoonim** [unjs/unstorage#172]
### Environment

centos9 stream
node 18
yarn
nuxt 3.2.3

### Reproduction

in nuxt.config.ts:
```
...
  nitro: {
    compressPublicAssets: true,
    storage: {
      redis: {
        driver: 'redis',
        port: 6379,
        host: '172.25.176.5',
        username: 'a',
        password: 'a',
        db: 0,
      },
    },
  },
...
```

in server:
```
await useStorage().setItem('redis:blah', 'blah')
```

in console:
```
Redis driver requires either a host, url or cluster option
```

### Describe the bug

Happened today after upgrading to nuxt 3.2.3,
Yesterday it was fine.

### Logs

```sh
[nuxt] [request error] [unhandled] [500] Redis driver requires either a host, url or cluster option                                                                               19:56:21
  at getRedisClient (./node_modules/unstorage/drivers/redis.mjs:10:13)                                                                                                            19:55:38
  at getItem (./node_modules/unstorage/drivers/redis.mjs:30:27)  
  at asyncCall (./node_modules/unstorage/dist/shared/unstorage.c2211058.mjs:9:26)  
  at getItem (./node_modules/unstorage/dist/index.mjs:117:14)  
  at redisGet (./.nuxt/dev/index.mjs:11925:21)  
  at getCachedDesigns (./.nuxt/dev/index.mjs:12355:16)  
  at ./.nuxt/dev/index.mjs:12365:23  
  at ./node_modules/h3/dist/index.mjs:1140:47  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1196:19)
```

**Comment by minkoonim** [comment]
![image](https://user-images.githubusercontent.com/38183949/222425449-692191b4-f09d-4ec0-a4a0-8c7316b877d1.png)
console shows exact configuration from my nuxt.config.ts
It's obvious "host" is provided

![image](https://user-images.githubusercontent.com/38183949/222425773-078327c5-4fc1-4d53-b52b-17a8ee882024.png)
added 
```
&& !opts.host
```

works fine.

**Comment by ronenteva** [comment]
I have the same issue exactly with the latest version.
Works fine with `1.1.5`.

**Comment by jamwong-ecosa** [comment]
I think there is no need to throw the error as host can be omitted 

const getRedisClient = () => {
    if (redisClient) {
      return redisClient;
    }

    **// not nedded**
    if (!opts.url && !opts.cluster) {
      throw new Error(
        "Redis driver requires either a host, url or cluster option"
      );
    }

   **// already checked the existence of the 2 keys**
    if (opts.cluster) {
      redisClient = new Redis.Cluster(opts.cluster, opts.clusterOptions);
    } else if (opts.url) {
      redisClient = new Redis(opts.url, opts);
    } else {
      redisClient = new Redis(opts);
    }
    return redisClient;
  };

**Comment by AloisSeckar** [comment]
I was happy to find [example of easy Redis integration](// https://nuxt.com/docs/guide/directory-structure/server#server-storage) right in the Nuxt docs, but unfortunatelly I ran into this problem as well.

Tried to override unstorage to `1.1.5` as suggested above, but it didn't help me.

**Comment by pi0** [comment]
Sorry for all inconvenience this regression appreciated in a refactor. For a hotfix, i have removed the strict checks fixing soon (you can use `nuxi upgrade --force` in order to update lockfile and receive the fix)

**Comment by AloisSeckar** [comment]
I can confirm the error disappeared and the app starts correctly now, thank you a lot for fast fix. 

Just got a little worried when nuxi claimed the current nuxt version is `3.0.0-rc.14` :o
![image](https://user-images.githubusercontent.com/7399922/223779817-8f708788-8b54-4c7e-ad3f-9de28ce3b854.png)

**Comment by danielroe** [comment]
@AloisSeckar what version of nuxt was in your `package.json`?

**Comment by AloisSeckar** [comment]
> @AloisSeckar what version of nuxt was in your `package.json`?

I had there `3.2.3` (without the carret ^)

But detail I forgot to mention - because I didn't have nuxi installed, I ran the command via npx: `npx nuxi upgrade --force`

But it seems to be the same even after installation:
![image](https://user-images.githubusercontent.com/7399922/224325489-e67d258c-7035-4079-9253-7688a0a03e98.png)

My package.json fragment with dependencies:

```json
"devDependencies": {
    "@nuxtjs/eslint-config-typescript": "12.0.0",
    "@vitest/coverage-c8": "0.29.2",
    "eslint": "8.35.0",
    "nuxt": "3.2.3",
    "openapi-typescript": "5.4.1",
    "sass": "1.58.3",
    "vitest": "0.29.2"
  },
  "dependencies": {
    "@pinia/nuxt": "0.4.7",
    "devextreme": "22.2.4",
    "devextreme-vue": "22.2.4",
    "pinia": "2.0.32"
  },
```

**Comment by danielroe** [comment]
Do you have a monorepo format?
