### ISSUE TITLE
Duplicate colons for redis base key

### ISSUE THREAD

**Issue by ronenteva** [unjs/unstorage#176]
### Environment

unstorage `1.3.0`

### Reproduction

```
nitro: {
    storage: {
      cache: {
        driver: 'redis',
        host: 'redis-host',
        base: 'example:'
      }
    }
  }
```

unstorage 1.2.0: `example:nitro:handlers:_:...`
unstorage 1.3.0: `example::nitro:handlers:_:...`

### Describe the bug

-

**Comment by pi0** [comment]
This should be fixed in next release (82647e06dc60b00f80a97c6646edee6688586959). I am so sorry for regression.
