### ISSUE TITLE
Should the optionalDependencies actually be peerDependencies marked as optional?

### ISSUE THREAD

**Issue by bradlis7** [unjs/unstorage#180]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

Right now, all of these azure packages are loaded into my node_modules, and people that need it should probably explicitly install it.

Perhaps marking it as an optional peerDependency would be better?

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependencies
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta

**Comment by pi0** [comment]
Hi. Latest release have them as optional peer.
