### ISSUE TITLE
[Question] Why those packages both in dev and optional?

### ISSUE THREAD

**Issue by maicss** [unjs/unstorage#182]
### Environment

None

### Reproduction

None

### Describe the bug

My nodejs version is 19.1.0
 When I install my nuxt project:

`@nuxt/content@2.5.2 => unstorage@1.4.0 => @azure/identity@3.1.3 => @azure/msal-node/1.16.0`
`@azure/msal-node/1.16.0` needs node version: `10 || 12 || 14 || 16 || 18`

But I didn't understand is why this project list those package:
```
    "@azure/app-configuration": "^1.3.1",
    "@azure/cosmos": "^3.17.3",
    "@azure/data-tables": "^13.2.1",
    "@azure/identity": "^3.1.3",
    "@azure/keyvault-secrets": "^4.6.0",
    "@azure/storage-blob": "^12.13.0",
    "@planetscale/database": "^1.6.0"
```

**Comment by pi0** [comment]
Hi. Can you share your package manager's name and version?

**Comment by pi0** [comment]
Thanks for report. Will be fixed in next release to not install those deps.
