### ISSUE TITLE
Duplicate line

### ISSUE THREAD

**Issue by ManUtopiK** [unjs/unstorage#189]
https://github.com/unjs/unstorage/blob/cca7ebf49fbbc12640af675d5c6ef4e8a7f24ad9/src/index.ts#L17-L19

**Comment by thetejasmagade** [comment]
Hey @pi0, Should I update?

**Comment by pi0** [comment]
Sure feel free to make a pr

**Comment by NozomuIkuta** [comment]
Let me close this issue since the PR has been already merged.
