### ISSUE TITLE
support `setItems` and `getItems` for operation batching

### ISSUE THREAD

**Issue by ManUtopiK** [unjs/unstorage#198]
### Describe the feature

I'm currently building a driver for gitlab. #199 
I just forked the github driver, write tests, adapted `fetchFiles` and `getItem` for gitlab api, and done !

What I want to do is to provide a feature to `setItem` with a `create/commit` http post request.
But I don't want to commit each files one by one, I want to commit a bunch of files, with a commit message passed in `opts` and update the store internally with the http response.

A `setItems` function could be useful to do that. I think it could also be implemented for the github driver.
 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by ManUtopiK** [comment]
Maybe also `getItems`, to fetch a bunch of files in one shot...

**Comment by pi0** [comment]
Both seems good ideas for support operation batching! PR more than welcome 💯
