### ISSUE TITLE
Integration with nuxt-community/universal-storage-module

### ISSUE THREAD

**Issue by farzadso** [unjs/unstorage#20]
Hi there,

I was thinking about using unstorage as the main storage handling layer in [https://github.com/nuxt-community/universal-storage-module](https://github.com/nuxt-community/universal-storage-module)

What do you think?

**Comment by pi0** [comment]
Hi Farzad sorry for late response. I think it would be nice idea to use try. Moving to https://github.com/nuxt-community/universal-storage-module/issues/195
