### ISSUE TITLE
Support raw data

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#21]
Plan:
- Use [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) or [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) (universal)
- Node.js [`Buffer`](https://nodejs.org/api/buffer.html) converting support
- Detect raw types for `setItem` and serialize with `base64`
  - Allow drivers to specify if they natively support raw data storage (`fs`) and skip serialize
- Support flag for `getItem` to get raw data without deserialization

**Comment by stafyniaksacha** [comment]
Hello @pi0

What do you think about handling blob with other helpers like:
- `await setBlob('key', blobLike)`
- `const blobLike = await getBlob('key')`

We may need to create a `unblob` library that wrap:
- Node.js Blob: https://nodejs.org/api/buffer.html#class-blob
- WebApi Blob: https://developer.mozilla.org/en-US/docs/Web/API/Blob

The main advantage I see to separate both items/blob is that blob can then be streamed. We can then imagine implementing custom [TransformStream](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream/TransformStream) for [encrypted storage](https://github.com/unjs/unstorage/issues/24), compressing/decompressing, read/write progress, etc...

```ts
const storage = createStorage({})

storage.mount('/output', fsDriver({ 
  base: './output',

  // this option is available depending on the driver used
  blob: {
    enabled: true,
    transformers: {
      read: [],
      write: [],
    }
  }
}))

const blob = new Blob(['<p>hello world</p>'], { type: 'text/html' })
await storage.setBlob('/output/test.html', blob)

const saved = await storage.getBlob('/output/test.html')
console.log(saved.size, saved.type)
console.log(saved.stream())
```

**Comment by benatkin** [comment]
If it could handle anything that could be passed to here, I think that would make it easier to support use cases like h3. https://w3c.github.io/IndexedDB/#value-construct

**Comment by pi0** [comment]
Followup https://github.com/unjs/unstorage/issues/21
