### ISSUE TITLE
expose underlying client instance

### ISSUE THREAD

**Issue by BlackoutGG** [unjs/unstorage#210]
### Describe the feature

There are many situations where having the client returned and painlessly accessible every where in your app is a necessity. In a scenario like redis where you need access to functionality like unlink or scanStream that aren't offered by unstorage, or other db drivers and you need more granular control.

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
Excellent idea.

**Comment by pi0** [comment]
Landed via #446
