### ISSUE TITLE
`vercel-kv` driver

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#218]
Initial support for `vercel-kv` driver added in https://github.com/unjs/unstorage/pull/213.

The platform feature itself is in beta, please check [Vercel KV Limits](https://vercel.com/docs/storage/vercel-kv/limits) for more info.

----

While testing and adding tests, I discovered some issues: 

- For node.js environments, `fetch` polyfill is required (Node 16). We might need to either document it or add polyfill to driver or upstream. (nuxt and nitro already polyfill fetch)
- Driver import (even if not used!) fails since `@vercel/kv` requires `KV_REST_API_URL` and `KV_REST_API_TOKEN` for its default export. (it works when bundled only with rollup/nitro/nuxt/etc). Needs more investigation. Might be only issue with `vitest`.

**Comment by MickL** [comment]
Hey @pi0 , I tried to use the driver in my Nuxt project using `nuxt-security` but I cant see anything in my Vercel KV (Redis) using `KEYS *`

Weirdly the rate limiting is actually working. Maybe with a misconfiguration it falls back to the default driver?

What I dont understand from the docs is: Am I supposed to add `url` and `token` to the options or does the driver grab them from process.env itself? Shouldnt the following be enough to make it work?

```ts
import vercelKVDriver from 'unstorage/drivers/vercel-kv';

export default defineNuxtConfig({
  modules: ['nuxt-security'],
  security: {
    rateLimiter: {
      tokensPerInterval: 150,
      interval: 300000,
      driver: vercelKVDriver({}),
    },
  },
});
```

Issue over at nuxt-security: https://github.com/Baroshem/nuxt-security/issues/372
