### ISSUE TITLE
Cloudflare Workers: Cannot perform I/O on behalf of a different request.

### ISSUE THREAD

**Issue by zsilbi** [unjs/unstorage#219]
### Environment

Cloudflare Workers (non-module)
Nuxt 3.4.3
nitropack@2.3.3
unstorage: 1.5.0

### Reproduction

Deploy a high traffic Nuxt 3 site to CF workers.
Check logs pushed by Cloudflare Logpush.

### Describe the bug

We deployed a streaming site a few days ago, expecting high traffic from the first day.
Our workers currently process more than 1000 requests per second during peak hours with a 99.99% success rate which I am very satisfied with. 

The only type of error I see is in the log so far is the following:

**Error: Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request’s handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance.**

Fortunately, from the response codes it seems like the client does not experience these issues.

### Logs

```sh
{
  "Event.RayID": "7c49cad46a9ab51e",
  "Event.Request.Method": "GET",
  "Event.Request.URL": "/apple-touch-icon-precomposed.png",
  "Event.Response.Status": 200,
  "EventTimestampMs": 1683633733840,
  "EventType": "fetch",
  "Logs[0].Level": "error",
  "Logs[0].Message[0]": "Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall p ... <<<Logpush: message truncated>>> ... hRaw (worker.js:3113:395)",
  "Logs[0].Message[1]": "[nuxt] [request error] [unhandled] [500]",
  "Logs[0].TimestampMs": 1683633733984,
  "Logs[1].Level": "error",
  "Logs[1].Message[0]": "Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall p ... <<<Logpush: message truncated>>> ... hRaw (worker.js:3113:395)",
  "Logs[1].Message[1]": "[nuxt] [request error] [unhandled] [500]",
  "Logs[1].TimestampMs": 1683633733984,
  "Outcome": "ok",
  "plugin.type": "cloudflare",
  "ScriptName": "my_script",
  "timestamp": 1683633764248
}
```
```

**Comment by Hebilicious** [comment]
@zsilbi Could you provide a reproduction ?

**Comment by zsilbi** [comment]
I think this was an issue in the KV asset handler itself. I haven't seen this pop up for weeks, so I am closing this. Thanks!
