### ISSUE TITLE
getItemRaw() on PNG returns null

### ISSUE THREAD

**Issue by bart** [unjs/unstorage#222]
### Environment

Node: 18.6.0
NPM: 8.19.2
unjs/unstorage: 1.6.0

### Reproduction

Hopefully description is enough here

### Describe the bug

On a brand new Nuxt 3 project I'm using the Nitro Custom Server Assets feature to access files from public folder on server-side API. To access one of the files I'm using the `getItemRaw()` method expecting the buffer as a result but getting `null` instead.

```
// Nitro config
serverAssets: [{
  baseName: 'public',
  dir: '../public'
}]

// Server-side API
const imageBuffer = await useStorage('assets:public').getItemRaw('x.png')
console.log(imageBuffer) // <--- returns null
```

### Additional context

Looks like driver is `memory` when used with Nuxt. Could this be an issue?
I also described the problem here: https://github.com/unjs/nitro/discussions/1230

**Comment by maou-shonen** [comment]
#142 
I haven't looked into it further, but I came across this. 

( in `fs` driver, I have not tested other drivers)
```ts
await useStorage('assets:public').getItemRaw('x.png') // not work, get null
await useStorage().getItemRaw('assets:public:x.png') // work
```

**Comment by bart** [comment]
Thanks a lot @maou-shonen
That really solved the issue but seems to be an issue, anyway right? What do you think?

Cheers!

**Comment by bart** [comment]
@maou-shonen It's weird. It works in dev but when you build it and run `npm run preview` it returns file contents instead of buffer. I don't understand why.

**Comment by maou-shonen** [comment]
> @maou-shonen It's weird. It works in dev but when you build it and run `npm run preview` it returns file contents instead of buffer. I don't understand why.

Maybe you can provide a minimal reproduction?

**Comment by bart** [comment]
I found another solution. Using base64 images now so that I don't that extra loop with `useStorage()`. Might be more a Nuxt issue and not so much an Unstorage one, right?

**Comment by maou-shonen** [comment]
Hmm... I'm not sure.
In my use case, I only use redis and custom driver,
and I haven't encountered the issue you described in my testing environment.

**Comment by pi0** [comment]
Hi. Without a reproduction it is hard to tell what is wrong but i guess unlikely an issue with unstorage itself. (You might probably used a wrong `base` for `fs` driver in production since i see dir is relative path).

Please open an issue in either Nitro or Nuxt with reproduciton would be more than happy to help 🙏🏼
