### ISSUE TITLE
Snapshot not working with localStorage with base configured

### ISSUE THREAD

**Issue by Timbological** [unjs/unstorage#241]
### Environment

Unstorage: 1.6.0
Node: 19.9.0

### Reproduction

```
import { createStorage, snapshot } from 'unstorage'
import localStorageDriver from 'unstorage/drivers/localstorage'
const storage = window.localStorage
const localStorage = createStorage({
  driver: localStorageDriver({ base: 'app', localStorage: storage })
})
await localStorage.setItem('key', 'value')
const data = await snapshot(localStorage, "app");
console.log(JSON.stringify(data))
```
Result will be: {"key":null}

### Describe the bug

When localStorage is configured with a base the snapshot function does not work.

This is because in the snapshot function in [storage.ts](https://github.com/unjs/unstorage/blob/main/src/storage.ts):
```
export async function snapshot(
  storage: Storage,
  base: string
): Promise<Snapshot<string>> {
  base = normalizeBaseKey(base);
  const keys = await storage.getKeys(base);
  const snapshot: any = {};
  await Promise.all(
    keys.map(async (key) => {
      snapshot[key.slice(base.length)] = await storage.getItem(key);
    })
  );
  return snapshot;
}
```
The value comes from `await storage.getItem(key)` but the key includes the base eg. "app:key" which return null because it's not expecting the base. 
Changing to `await storage.getItem(key.slice(base.length))` works in this case

**Comment by Timbological** [comment]
I found it works if I use prefixStorage instead of setting the base in the localStorageDriver options
```
import { createStorage, snapshot, prefixStorage } from 'unstorage'
import localStorageDriver from 'unstorage/drivers/localstorage'
const storage = window.localStorage
const localStorage = createStorage({
  driver: localStorageDriver({ localStorage: storage })
})
const prefixedStorage = prefixStorage(localStorage, "app")
await prefixedStorage.setItem('key', 'value')
const data = await snapshot(prefixedStorage);
console.log(JSON.stringify(data))
```

**Comment by VladimirCores** [comment]
Simple switch to `memory` storage solve the issue, but I need `fs` (PS its part of "nuxt": "^3.8.1")

![image](https://github.com/unjs/unstorage/assets/442111/64b26e28-7637-4bc1-84fc-63de0301545d)

**Comment by MatteoGauthier** [comment]
It's not working also with Node.js lite drive

**Comment by pi0** [comment]
Hi. It seems related to base support issue in local storage. Let's track via https://github.com/unjs/unstorage/issues/352
