### ISSUE TITLE
[cloudflare] kv-http tests are disabled for node > 18

### ISSUE THREAD

**Issue by Hebilicious** [unjs/unstorage#257]
### Environment

NodeJS: v20.2.0
Unstorage: 1.7.0

### Reproduction

Runs the tests with node 18 +

### Describe the bug

Tests should be enabled against all node versions

### Additional context

This gets unblocked by upgrading msw to the latest version and running all test against node 18+
As node 18 LTS ends in 3 months, we should prepare and move the tests/CI to node 20.

**Comment by itpropro** [comment]
We have a lot of disabled/skipped tests currently and some others that are very flaky.
Maybe we can have a consolidated issue to track tests for the different drivers, why they are skipped/disabled, which ones have no reliable mock/emulator available and which ones are limited by a specific node version or even a specific runtime (node, deno, cf workers, etc.).
