### ISSUE TITLE
 standard key expiration for all supported drivers

### ISSUE THREAD

**Issue by Hebilicious** [unjs/unstorage#262]
### Describe the feature

Implement a `ttl` top level option for setting a ttl in seconds at the object level for all drivers.

```ts
await setItem(key, item, { ttl: 30 })
```

### Additional information

- Github driver supports global a global ttl option that isn't related to expiration
- Redis driver supports global and setItem ttl options that are related to expiration

For unsupported / partial support drivers, a manual expiration can be implemented by attaching custom unstorage metadata to the storage itself. 

#### Unsupported drivers

- [x] [Azure App configuration](https://stackoverflow.com/questions/73705193/caching-options-for-azure-app-configuration-with-js-sdk)
- [x] [Azure Storage Table](https://stackoverflow.com/questions/9025755/azure-table-storage-expiration)
- [x] fs
- [x] github
- [x] http (altough we could forward ttl to cache-control max age I don't think it makes sense)
- [x] planetscale
- [x] localstorage 
- [x] session-storage
- [x] memory (We could implement with `setTimeout`)

#### Partial support drivers

- [x] R2: This can be set at the [bucket level](https://developers.cloudflare.com/r2/buckets/object-lifecycles/), but not at the object level
- [x] [mongodb](https://www.mongodb.com/docs/manual/tutorial/expire-data/#expire-documents-after-a-specified-number-of-seconds): requires extra indexes

```[tasklist]
### TTL driver native support
- [ ] https://github.com/unjs/unstorage/pull/271
- [x] redis driver
- [ ] https://github.com/unjs/unstorage/issues/266
- [ ] https://github.com/unjs/unstorage/issues/32
- [ ] https://github.com/unjs/unstorage/pull/289
- [ ] Azure Cosmos
- [ ] Azure KV
- [ ] Azure SB
- [ ] lru-cache
```

- [X] Would you be willing to help implement this feature?

**Comment by YTaoger** [comment]
When will this feature be updated?🚀@Hebilicious

**Comment by itpropro** [comment]
I will implement this for the Azure Key Vault and the CosmosDB driver, but Azure Storage Table/Blob and Azure App Config are definitely unsupported natively.
For the general approach, I am not really sure what the benefit is for having the ttl in the metadata treated in another way than normal metadata. I would prefer to just support ttl in a standard way where it is natively supported and leave the rest to custom metadata fields defined by the user.
Otherwise we would have to create our own deletion mechanism that is triggered when a item is pulled from the source system and then checks if the ttl is expired. If yes, it would delete the item and behave like it didn't exist, if ttl is not expired, it would return it.
What is your input on this @pi0? I would be happy to draft a general ttl implementation for unsupported drivers, if you think it's in the scope of unstorage.

**Comment by Hebilicious** [comment]
> I will implement this for the Azure Key Vault and the CosmosDB driver, but Azure Storage Table/Blob and Azure App Config are definitely unsupported natively. I would also consider mongoDb as unsupported, as creating ttl indexes has a lot of implications and edge cases to be considered. For the general approach, I am not really sure what the benefit is for having the ttl in the metadata treated in another way than normal metadata. I would prefer to just support ttl in a standard way where it is natively supported and leave the rest to custom metadata fields defined by the user. Otherwise we would have to create our own deletion mechanism that is triggered when a item is pulled from the source system and then checks if the ttl is expired. If yes, it would delete the item and behave like it didn't exist, if ttl is not expired, it would return it. What is your input on this @pi0? I would be happy to draft a general ttl implementation for unsupported drivers, if you think it's in the scope of unstorage.


I agree with you, I listed both mongodb and r2 under possible but not straighforward, but maybe my wording is not strong enough, I'll rename this to partial support. In both cases it would be pretty hacky or as you said a custom deletion mechanism.
Regarding the general approach, this PR is to harmonize the drivers that support native TTL, ie to avoid contributors using a different key (`exp`, `settings.ttl` ...) or unit.
@itpropro Do you think Azure T/B and Azure AC are in unsupported, or in partial support ? I'll move them in partial support for now, but feel free to correct me.

**Comment by pi0** [comment]
At this point i think there is really no point of having such tracker. There is no **new shared feature** to implement other than adding types for `ttl?` as optional param. PR welcome to add (native) `ttl` option to any driver can accept it.

---

> Regarding the general approach, this PR is to harmonize the drivers that support native TTL, ie to avoid contributors using a different key (exp, settings.ttl ...) or unit.

I will make sure of that before merging any PRs if they used another key :)

**Comment by midzdotdev** [comment]
@pi0 When using an instance (with any driver) implementing the abstract `Storage` interface of knowing whether `ttl` is an option that will be respected by the implementation?

It would be nice for example to be able to do `storage.hasFeature('ttl')` so we know whether passing `ttl` to `setItem` will have any effect and as a result not have to execute some custom expiration handling code.
