### ISSUE TITLE
key expiration support for vercel-kv driver

### ISSUE THREAD

**Issue by azophy** [unjs/unstorage#266]
### Describe the feature

From what I found, current `vercel-kv` driver for unstorage does not provide `ttl` option. Meanwhile the `@vercel/kv` library does provide this option.

https://vercel.com/docs/storage/vercel-kv/kv-reference#set-example

I'm trying to follow the interface used by existing redis driver and implement it in vercel-kv driver. If there are no one working on this, I'm willing to help

my WIP: https://github.com/azophy/unstorage

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR is welcome 💯
