### ISSUE TITLE
Support MongoDB on Edge Runtime

### ISSUE THREAD

**Issue by nathanclevenger** [unjs/unstorage#270]
### Describe the feature

Currently MongoDB support is provided by the NodeJS driver and is not supported on edge runtimes.  I would propose adding additional support for MongoDB through either the Atlas Data API and/or Realm Web SDK which will run on edge runtimes like Cloudflare Workers and the Vercel Edge Runtime.

If this is an acceptable proposal, I would be willing to contribute a PR.  Thanks.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Sure a new driver for `mongodbAtlasData` would be nice 👍🏼 (found docs here https://www.mongodb.com/docs/atlas/api/data-api/)

**Comment by Hebilicious** [comment]
There's also `mongodbRealm` that we can consider https://www.mongodb.com/docs/realm/sdk/node/quick-start/#create--modify--and-delete-realm-objects

**Comment by pi0** [comment]
Since for KV usage, we need simple operations, i prefer to use Data API with native fetch if possible :)

**Comment by pi0** [comment]
Canceling as there seems not enough intrest in this. If anyone interested to contribute and make a driver for MongoDB atlas (or any other mongo-over-http provider) PRs are more than welcome.

Cludflare Worker team is also working on compatibility for MongoDB via Node compat flag, you can track from https://github.com/cloudflare/workerd/discussions/2721#discussioncomment-11497490
