### ISSUE TITLE
fs driver throws error when the option object is not modifable or it's properties are read only

### ISSUE THREAD

**Issue by gbalcewicz** [unjs/unstorage#274]
### Environment

node: v18.16.1
nuxt: 3.6.5
@sidebase/nuxt-session: 0.2.7

### Reproduction

Use fs driver for node session
```js
export default defineNuxtConfig({
  modules: [
    '@sidebase/nuxt-session',
  ],
 session: {
    api: {
      isEnabled: false,
    },
    session: {
      storageOptions: {
        driver: 'fs',
        options: {
          base: '/tmp',
        },
      },
    },
}
```

### Describe the bug

When using fs driver with nuxt session plugin I'm getting errors like `Cannot assign to read only property 'base' of object '#<Object>'` or `Cannot add property ignore, object is not extensible`

This is becaus of operating on the options argument
```ts
  if (!opts.ignore) {
    opts.ignore = ["**/node_modules/**", "**/.git/**"];
  }

  opts.base = resolve(opts.base);
```

**Comment by Hebilicious** [comment]
Should we change this behaviour @pi0 ? I think it makes sense for unstorage to inject ignore options, but maybe we shouldn't be modifying the original object.

**Comment by pi0** [comment]
We might avoid mutating driver options as a best practice however the linked project is archived and it is not clear why options were fronzen.

**Comment by sandros94** [comment]
I just discovered this. my goal was to create a runtime plugin in Nitro and be able to edit the base path at runtime (for example same containerized image but different persistent volume path).

this seems counter intuitive as I have to rely on:

```ts
import fsDriver from 'unstorage/drivers/fs'

import { defineNitroPlugin, useRuntimeConfig, useStorage } from '#imports'

export default defineNitroPlugin(() => {
  const storage = useStorage()
  const options = useRuntimeConfig().fs!

  const driver = fsDriver({
    base: options.base,
    ignore: options.ignore,
    noClear: options.noClear,
    readOnly: options.readOnly,
    watchOptions: options.watchOptions,
  })

  storage.unmount('fs')
  storage.mount('fs', driver)
})
```

Is this for grab on a PR?
