### ISSUE TITLE
Support for Capacitor Preferences API

### ISSUE THREAD

**Issue by Marcoru97** [unjs/unstorage#279]
### Describe the feature

Capacitor-js is a layer around a web app to ship web apps as native Apps (Similar to electron). `@capacitor/preferences` is a key/value store that read/writes to the native OS. Would be great if we could access it through unstorage!

https://capacitorjs.com/docs/guides/storage

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the suggestion. Looking at the docs, supporting preferences storage is a good idea! PR more than welcome!

Re SQL, there is an upcoming unjs package (db0), sqlite would be a really nice match for it. I will add it to the list and try to ping you once public if you like to help on that too.

(the plan is later we support one `unstorage` driver `sql` that uses other lib)
