### ISSUE TITLE
How to use other api of redis?

### ISSUE THREAD

**Issue by szmxx** [unjs/unstorage#282]
### Describe the feature

When I choose driver as redis, I want to use hgetall api, but it prints as undefined.
```ts
    import { createStorage } from "unstorage";
    const storage = createStorage(/* opts */);
    console.log('redis', storage.hgetall) // undefined
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by BlackoutGG** [comment]
unstorage doesn't support hgetall, nor stuff like scanStream.

Would be great to have access to the underlining client through unstorage for use cases like this tho.

**Comment by szmxx** [comment]
> unstorage doesn't support hgetall, nor stuff like scanStream.
> 
> Would be great to have access to the underlining client through unstorage for use cases like this tho.
> 
> It's super unfortunate, and the main reason why I don't use it anymore, especially with nuxt 3.

It would be great if the client could be exposed. if only use the get set api in such a limited way, it will lose the meaning of using redis. Is there any alternative?

**Comment by xlanex6** [comment]
@szmxx 

I personally use [IOREDIS](https://github.com/redis/ioredis), place on `utils` folder and export as `$redis`. 
I can use CLIENT side and SERVER SIDE , but server side I use REad only key .

You have to keep in mind that ioredis use TCP, so you CAN NOT deploy on edge function. 
Serverless functions works well .

**Comment by pi0** [comment]
Hi. For more flexibility, you can always directly use a connector client such as io redis. 

In the future we might allow accessing connector instance from driver to make it easier initializing client once.
