### ISSUE TITLE
Dragonfly driver (Redis)

### ISSUE THREAD

**Issue by oritwoen** [unjs/unstorage#294]
### Describe the feature

Dragonfly is referred to as the modern version of Redis and The Fastest In-Memory Data Store.

> In benchmarks, Dragonfly showed a 25X increase in throughput compared to Redis, crossing 3.8M QPS on c6gn.16xlarge.

- https://www.dragonflydb.io/

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
https://github.com/unjs/unstorage/pull/353#issuecomment-2546815306
