### ISSUE TITLE
The `prefixStorage` should has a method to retrieve the full key

### ISSUE THREAD

**Issue by bytemain** [unjs/unstorage#303]
### Describe the feature

after created a `prefixStorage`, I want log the full key if the key is not found on the storage, now I need construct it by myself.

```ts
interface PrefixStorage extends Storage {
  retrieveKey(path: string): string;
}
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi and sorry for the late reply.

Considering this issue is old, I'm not sure if your feature is relevant or not, but if you can explain your use-case better, would be happy to open to discuss.
