### ISSUE TITLE
Allow using `/` as the path separator

### ISSUE THREAD

**Issue by bytemain** [unjs/unstorage#304]
### Describe the feature

Before I found this library, I am using `/` as the key separator.

and now I want to use this library in my codebase, but Storage always construct key as `a:b:c`

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by bytemain** [comment]
This is not easy, and it will be a breaking change for all.

![CleanShot 2023-09-27 at 11 46 58@2x](https://github.com/unjs/unstorage/assets/13938334/72aef988-a28a-408c-8b08-e8ed7c66c90f)
and there also are functions that already in used.

**Comment by pi0** [comment]
That's correct. What i plan is to support encodeKey utilities to allow this characters.

**Comment by bytemain** [comment]
I made my first implementation for this, I will make a pr later

**Comment by pi0** [comment]
Moving to https://github.com/unjs/unstorage/issues/437
