### ISSUE TITLE
Node fs driver not parsing JSON correctly on `getItem`

### ISSUE THREAD

**Issue by ganchoradkov** [unjs/unstorage#313]
### Environment

env: `nodejs`
package: `"unstorage": "^1.9.0"`
driver: `"unstorage/drivers/fs-lite"`

### Reproduction

JSON data saved using `setItem`
```json
[
   {
      "id":1696432843813494,
      "topic":"a010c720914211446fa00fbab9ba09f6960ff4b0fe08640da5aaa302893347a4",
      "request":{
         "method":"wc_sessionPropose",
         "params":{
            "requiredNamespaces":{
               
            },
            "optionalNamespaces":{
               
            },
            "relays":[
               {
                  "protocol":"irn"
               }
            ],
            "proposer":{
               "publicKey":"89df667763a718f5b254e32c7306a579b2653cb9810e3f3f4309ba0fdfbdc876",
               "metadata":{
                  "name":"Test App",
                  "description":"Test App for WalletConnect",
                  "url":"https://walletconnect.com/",
                  "icons":[
                     "https://avatars.githubusercontent.com/u/37784886"
                  ]
               }
            }
         }
      },
      "expiry":1699024843,
      "response":{
         "result":{
            "relay":{
               "protocol":"irn"
            },
            "responderPublicKey":"ed505a321885bc4452549e34eec5e69b57dce55a7614150a82331be024b42e0c"
         }
      }
   },
   {
      "id":1696432844531432,
      "topic":"c81eb451fafb2f5128b13a1788542b47d7f84bb148a27f63f63a51c60dad32e2",
      "request":{
         "method":"wc_sessionPing",
         "params":{
            
         }
      },
      "expiry":1699024844,
      "response":{
         "result":true
      }
   }
]
```

data returned by `getItem`
```json
[
   {
      "id":1696432843813494,
      "topic":"a010c720914211446fa00fbab9ba09f6960ff4b0fe08640da5aaa302893347a4",
      "request":{
         "method":"wc_sessionPropose",
         "params":{
            "requiredNamespaces":{
               
            },
            "optionalNamespaces":{
               
            },
            "relays":[
               {
                  "protocol":"irn"
               }
            ],
            "proposer":{
               "publicKey":"89df667763a718f5b254e32c7306a579b2653cb9810e3f3f4309ba0fdfbdc876",
               "metadata":{
                  "name":"Test App",
                  "description":"Test App for WalletConnect",
                  "url":"https://walletconnect.com/",
                  "icons":[
                     "https://avatars.githubusercontent.com/u/37784886"
                  ]
               }
            }
         }
      },
      "expiry":1699024843,
      "response":{
         "result":{
            "relay":{
               "protocol":"irn"
            },
            "responderPublicKey":"ed505a321885bc4452549e34eec5e69b57dce55a7614150a82331be024b42e0c"
         }
      }
   },
   {
      "id":1696432844531432,
      "topic":"c81eb451fafb2f5128b13a1788542b47d7f84bb148a27f63f63a51c60dad32e2",
      "request":{
         "method":"wc_sessionPing",
         "params":{
            
         }
      },
      "expiry":1699024844,
      "response":{
         "result":true
      }
   }
]{
   "id":1696432845108483,
   "topic":"c81eb451fafb2f5128b13a1788542b47d7f84bb148a27f63f63a51c60dad32e2",
   "request":{
      "method":"wc_sessionPing",
      "params":{
         
      }
   },
   "expiry":1699024845,
   "response":{
      "result":true
   }
}
]
```

### Describe the bug

I'm testing out the lib and run into an issue using the `fs-lite`driver. I'm saving the above stringified JSON but when I attempt to get the data using `getItem`, the JSON returned is malformed and unusable. I've checked the value stored in the actual file and formatting/contents are correct so the issue is happening when reading/parsing the JSON from the file.

Suggestion: 
Would be awesome if the lib allows you to provide custom parsing functions. In my org, we are using [`safe-json`](https://github.com/WalletConnect/walletconnect-utils/tree/master/misc/safe-json) lib to handle json payloads including `Bigint` although I'm not sure if the issue is related.

**Comment by pi0** [comment]
Hi. I have made a reproduction from the provided data above, but it seems the stored data is same:

https://stackblitz.com/edit/stackblitz-starters-og7qd4?file=package.json,index.mjs

Can you please try that? (it is possible something happened in concurrency, regardless of JSON serializer)


BTW it is a good idea to support custom serializer apart from this also if there is any issue with destr we shall fix it.

**Comment by ganchoradkov** [comment]
Thanks for the fast response. Indeed, in your sandbox it works so I would dig deeper what might be causing my issue 💯

**Comment by VladimirCores** [comment]
I'm facing the similar problem but with writing when `setItem` in loop, event when object is correct:
 ```{
  voluptatem: [
    { code: '43951', label: 'Sed quaerat estd.', value: 'jRJHnjJo7W' }
  ],
  voluptatibus: [ { code: '78261', label: 'Ullam deseru.', value: 'EFEY1xPTm6' } ]
}
```
the stored result is wrong:
```
"{\"voluptatem\":[{\"code\":\"43951\",\"label\":\"Sed quaerat estd.\",\"value\":\"jRJHnjJo7W\"}],\"voluptatibus\":[{\"code\":\"78261\",\"label\":\"Ullam deseru.\",\"value\":\"EFEY1xPTm6\"}]}Kf4QBH\"}]}"
```
and its completely unpredictable.

**Comment by VladimirCores** [comment]
Simple switch to memory storage solve the issue, but I need fs (PS its part of "nuxt": "^3.8.1")

![image](https://github.com/unjs/unstorage/assets/442111/9860cd0f-f85e-41a0-9e3a-204fa5345b72)

**Comment by VladimirCores** [comment]
`fsLite` also not working properly

**Comment by VladimirCores** [comment]
Looks like the problem was with ids, they were duplicated.

**Comment by pi0** [comment]
@VladimirCores Kindly please open new issue with runnable reproduction so I can check 🙏🏼

**Comment by VladimirCores** [comment]
@pi0 it was a problem on my side, the used [falso](https://github.com/ngneat/falso) random generator and looks like some of their generators (rndText, rndAbbreviation, rndCode) produce duplication on large sets, which resulted in node writing (overwriting) issue.
