### ISSUE TITLE
Add driver for myjson.online

### ISSUE THREAD

**Issue by codemers** [unjs/unstorage#325]
### Describe the feature

Would you be willing to accept a PR that adds a new driver for [myJSON](https://myjson.online
)? myJSON is a lightweight, JSON-based storage service that allows users to store JSON data in the cloud.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR more than welcome to add driver!

**Comment by pi0** [comment]
Hi, dear @codemers. I have spent some time reading docs and updating PR for adding the driver (see my comments: https://github.com/unjs/unstorage/pull/366#issuecomment-2546997975), it seems API does not allow setting items with a custom key which is a requirement for unstorage and sadly we cannot support current API as a driver.

If you planned to add this ability I would be glad to resurface this

 Cheers ❤️
