### ISSUE TITLE
Typo in the indexedb driver doc

### ISSUE THREAD

**Issue by penghuili** [unjs/unstorage#326]
### Environment

It's about document, no envrionment is needed.

### Reproduction

Open https://github.com/unjs/unstorage/blob/main/docs/content/6.drivers/indexedb.md

### Describe the bug

Open https://github.com/unjs/unstorage/blob/main/docs/content/6.drivers/indexedb.md

In the `Usage` part, it should be 
```
import indexedDbDriver from "unstorage/drivers/indexedb";
```

not 

```
import indexedDbDriver from "unstorage/drivers/indexeddb";
```

Screenshot:

<img width="560" alt="Screenshot 2023-10-22 at 12 34 09" src="https://github.com/unjs/unstorage/assets/5326739/4e104599-dfff-4f00-ab28-30660d1f89df">

**Comment by peterroe** [comment]
Nice catch.
