### ISSUE TITLE
[unstorage] [localstorage] Missing required option `localStorage`.

### ISSUE THREAD

**Issue by MotionPhix** [unjs/unstorage#332]
### Environment

Node 20.8.1
Unstorage 1.9.0

### Reproduction

Create new nuxt 3 app and initialize unstorage

### Describe the bug

When I initialize unstorage in a nuxt 3 app I am getting `[unstorage] [localstorage] Missing required option `localStorage`.` . I have tried to do it with sessionStorage, the same issue. Indexdb says indexDB cannot be found: Here is how I am initializing the package:

import { createStorage } from "unstorage";
import localStorageDriver from "unstorage/drivers/localstorage";
// import indexedDbDriver from "unstorage/drivers/indexedb";
  
const storage = createStorage<string | number>({
  driver: localStorageDriver({ base: 'leads:',  }),
});

async function hasItem(key: string) {
  return await storage.hasItem(key)
}

async function addItem(item: string | number) {
  await storage.setItem('token', item)
}

async function fetchItem(key: string) {
  return await storage.getItem(key)
}

async function deleteItem(key: string) {
  await storage.removeItem(key, { removeMeta: true })
}

async function deleteAll() {
  await storage.clear()
}

async function startWatch(key: string) {
  await storage.watch((event, key) => {
    console.log(key);  
  })
}

async function stopWatch() {
  await storage.unwatch();
}

export default storage;

export { addItem, deleteAll, deleteItem, fetchItem, hasItem, startWatch, stopWatch };

I haven't been successful in all my attempts. Could this be a bug with nuxt js 3?

**Comment by adeacetis** [comment]
Hey,
If you look at the code, the window object is required. It's unclear where you did set it up. Was it in the client or in the server repo?
Regards,

**Comment by pi0** [comment]
local storage driver can be used in browsers only
