### ISSUE TITLE
Documentation not loading any of the contents

### ISSUE THREAD

**Issue by oofdere** [unjs/unstorage#347]
### Environment

Chromium 119.0.6045.159 and Firefox 119.0.1

### Reproduction

n/a - Documentation bug

### Describe the bug

None of the contents of any of the documentation pages are visible. The table of contents does populate, though.

![image](https://github.com/unjs/unstorage/assets/43102807/28929998-d5f5-4136-8a11-0fb767d4a4d9)

**Comment by abdennor** [comment]
same here

**Comment by pi0** [comment]
Thanks for reporting. Docs should be working again 🎊

**Comment by pi0** [comment]
Up again https://unstorage.unjs.io/ 

We will be working with @Atinux to upgrade to newer docs infra to avoid such regressions in the future.
