### ISSUE TITLE
Support `Redis` options for `setItem`

### ISSUE THREAD

**Issue by ms-fadaei** [unjs/unstorage#35]
We need to support Redis options when using `setItem`.

Here is the part of my code in which I use `ioredis` to store data:
```js
client.set(index, data, "EX", TTL)
```

Currently, there is no way to accomplish this with `unstorage` Redis driver. How we can provide a way to support this in the `unstorage`?

**Comment by ms-fadaei** [comment]
I think this is related to #13

**Comment by BlackoutGG** [comment]
Still waiting for this; makes it hard to use unstorage without it. Also there's no visible way to extend the typescript definitions when it comes to adding additional functions like unlink and scanStream.

**Comment by McPizzaIs** [comment]
for Redis TTL, this could be addressed by #150
