### ISSUE TITLE
Driver class support

### ISSUE THREAD

**Issue by eligao** [unjs/unstorage#376]
### Describe the feature

Since the `Driver` is an interface, it is almost possible to write a class to extend it, then calling `new SomeDriver()` instead of invoking the `DriverFactory`.
The only blocker now is that `asyncCall()` dropped `this` for class methods.
TBH, I didn't get the point of `asyncCall()` here, it wraps a value/function into a Promise, which doesn't seem necessary since `await` can accept a non-promise?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi and thanks for suggestion. For now it is non-goal because object syntax allows extending behavior on core-level rather than driver-level.
