### ISSUE TITLE
Cached getItem helpers

### ISSUE THREAD

**Issue by acidjazz** [unjs/unstorage#379]
### Describe the feature

It would be cool to have some storage helpers wrapped around getItem to easily specify an expiration time, for example I just whipped up something like this:

```ts
export const getItemDay = async <Result>(key: string): Promise<Result|undefined> => {
  const item = await storage.getItem(key) as Result | undefined
  const meta = await storage.getMeta(key)
  return !item || meta.atime && (Date.now() - new Date(meta.atime).getTime()) > 86400000 ? undefined : item
}
```

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi, and thanks for the suggestion. Having cached storage makes sense and it is the oldest issue still open. Let's track via https://github.com/unjs/unstorage/issues/15 

(my plan is to introduce generic interceptor support and then extract caching functionality out of nitro to a genric lib we can leverage directly for unstorage cached storage)
