### ISSUE TITLE
uploadthing driver

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#389]
(context: found about uploadthing from https://github.com/unjs/h3/issues/628)

- https://uploadthing.com
- https://github.com/pingdotgg/uploadthing

Let's make uploads for *developers better ;) 

/cc @juliusmarminge @t3dotgg @markflorkowski let me know if likes to work to make it happen ❤️

**Comment by juliusmarminge** [comment]
We have Nuxt and Vue support coming but are currently blocked by a type bug in Vue https://github.com/vuejs/core/issues/10167

**Comment by pi0** [comment]
That's nice for Vue/Nuxt!! FYI, unstorage scope is a little bit different. It is more a backend layer that allows storing data in agnostic backends (like a filesystem) which can be retrieved to be for example served by another handler and not tied to Vue. Feel free to drop me a DM in X or discord (_pi0, pi0) if like to have a chat!

**Comment by pi0** [comment]
Experimental driver landed in #390
