### ISSUE TITLE
please: No breaking changes in patch versions 🙏

### ISSUE THREAD

**Issue by McPizza0** [unjs/unstorage#412]
### Describe the feature

v1.10.2 was released yesterday as a patch

it included breaking changes (requiring ioredis to be installed separately)

this broke our workflows when it was installed automatically as part of nitro (clean installs or deployments)

breaking changes like this should be delayed till a minor release, where we can opt into the updates

please and thank you 💚

https://github.com/unjs/unstorage/releases/tag/v1.10.2

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Sorry I understand that it might have cause inconveniences and it wasn't an easy decision because releasing a major version could have cause more ecosystem issues today. 🙏🏼 I think re peer dependencies we should be good now.

**Comment by pi0** [comment]
~> https://github.com/unjs/unstorage/issues/413
