### ISSUE TITLE
How to access all available stores

### ISSUE THREAD

**Issue by Rednas83** [unjs/unstorage#452]
Something like
`var stores = await useStorage.getItems() // Returns [store1: {value1: value}]`
or to just get the store names
`var stores = await useStorage.getItemsByName() // Returns [store1]`

Similar to what is possible with pinia
```
import { getActivePinia } from "pinia"
var stores = getActivePinia() // Returns [store1: {value1: value}]
```

**Comment by Rednas83** [comment]
Sorry, looks like there is already experimental support for it
![image](https://github.com/unjs/unstorage/assets/25219229/3933971b-81f3-4804-a819-60684efbbcf5)

Another question. How can you declare a universal store that can be accessed everywhere?

Tried something like
**composables/useStore.ts**
```
import { createStorage } from "unstorage"
export function store() {
  return createStorage()
}

```

**Comment by Rednas83** [comment]
Succesfully migrated pinia to unStorage🥳.

Fixed it by applying any to `useNuxtApp()` and moving it inside the composables
```
export async function save(iContent: string, iValue?: any) {
  const { $storage } = useNuxtApp() as any
```

Not ideal, but it works for now. Please let me know if there is a better solution

**Comment by Rednas83** [comment]
Also I would like to add create some shortcuts for easier access.

Something like
**plugins/storage.ts**
```
  return {
    provide: {
      init: init,
      storage: storage,
      codes: ref(await storage.getItem("codes")), // TODO shortcuts
      settings: ref(await storage.getItem("settings")), // TODO shortcuts
      motors: ref(await storage.getItem("motors")), // TODO shortcuts
      chart: ref(await storage.getItem("codes")), // TODO shortcuts
    },
  }
```
**app.vue**
`const { $codes, settings, motors, chart } = useNuxtApp()`

Is something like that possible?

**Comment by Rednas83** [comment]
Any thoughts?

**Comment by pi0** [comment]
You can use `storage.getMounts(base)` to get mount points for a subpath.
