### ISSUE TITLE
How to perform mutations inside a store

### ISSUE THREAD

**Issue by Rednas83** [unjs/unstorage#453]
Something like
```
store.patch({
  count: store.count + 1,
  age: 120,
  name: 'DIO',
})
```
OR
```
store.patch((state) => {
  state.items.push({ name: 'shoes', quantity: 1 })
  state.hasChanged = true
})
```

**Comment by Rednas83** [comment]
Sorry, just found it in the docs. Even possible with `setItem` I see. That's cool🚀
![image](https://github.com/unjs/unstorage/assets/25219229/1bb2f24e-f6ec-4c7d-baa2-d943ad44907e)

**Comment by Rednas83** [comment]
Any thoughts?

**Comment by pi0** [comment]
unstorage is a KV database you need one `getItem` + one `setItem`
