### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by warflash** [unjs/unstorage#465]
### Describe the feature

Creating a quick issue since discussions aren't enabled - I'd just like to say that there have been some quite nice changes since the last release a few months ago. 
Would be nice to perhaps get a new release, should it fit the schedule.
Thanks, and feel free to close 😊

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi, thanks, it will be released once ready.
