### ISSUE TITLE
How to return a reactive store (ref) that can be used for live updates on a page

### ISSUE THREAD

**Issue by Rednas83** [unjs/unstorage#471]
Something like
```
<template>
 {{ counter }}
</template>
<script setup>
  // const await storage.getItem("counter") // Only returns the value
  const counter = useStore('counter') // QUESTION: How to return a reactive store that can be used for live updates on a page
</script>
```

Is it possible or can it be added for convenience?

**Comment by pi0** [comment]
Unstorage is a KV layer, it doesn't include reactivity like vue or react (you can bind storage values to one)

**Comment by Rednas83** [comment]
...but that takes a lot of boilerplate code. Is it possible to add support for reactivity? Or would pinia be the recommended solution for this?

**Comment by pi0** [comment]
Yes, perhaps pinia is a better solution. You might create an unstorage instance with `localstorage` driver for example and periodically store state via `store.$state` (pinia)

**Comment by Rednas83** [comment]
I am not sure if I understand what you mean. Could you share a simple example with a counter?
