### ISSUE TITLE
Support raw storage for IndexedDB

### ISSUE THREAD

**Issue by ahmedrangel** [unjs/unstorage#511]
### Describe the feature

The driver always stores objects in a stringified form, which makes it more difficult to inspect properties when storing large objects.

I made a workaround by creating a custom indexedDB driver replacing this line:
https://github.com/unjs/unstorage/blob/e42c01d0c22092f394f57e3ec114371fc8dcf6dd/src/drivers/indexedb.ts#L40-L42

with:
```ts
setItem(key, value) {
  try {
    value = JSON.parse(value)
  }
  catch { /* use string value */ }
  return set(makeKey(key), value, customStore);
},
```

Viewed in `Application` tab:
- Current behavior:
![image](https://github.com/user-attachments/assets/f327390c-9222-4be0-8308-78afdd6ac51b)

- Workaround behavior:
![image](https://github.com/user-attachments/assets/a393c521-ff22-477f-9c71-4f0013934a69)

This workaround ensures that object values are stored as objects, otherwise they continue to be stored as strings.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Please check my comment in https://github.com/unjs/unstorage/pull/512#issuecomment-2531750434. PR welcome.
