### ISSUE TITLE
key and blob are reserved words in MySQL, so everything fails: table creation, retrieval, etc.

### ISSUE THREAD

**Issue by ernestoalejo** [unjs/unstorage#537]
### Environment

unstorage 1.14.1
node v20.18.0
mysql 8.0.33

### Reproduction

```js
import { createDatabase } from 'db0'
import mysql from 'db0/connectors/mysql2'

const db = createDatabase(
  mysql({
    database: createDatabase(mysql({ uri: process.env.DATABASE_URL })),
  }),
)
```

### Describe the bug

`key` and `blob` are reserved words and cannot be used in mysql without escaping them first.

It throws errors for example in [this line of code](https://github.com/unjs/unstorage/blob/main/src/drivers/db0.ts#L176):

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR(255) NOT NULL PRIMARY KEY,
        value LONGTEXT,
        blob BLOB,
```

And errors in other places [like this](https://github.com/unjs/unstorage/blob/main/src/drivers/db0.ts#L64):

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 'foo'' at line 1
```

### Additional context

Column names can be escaped with the "`" character though it might be inconvenient in Javascript because it breaks template strings. Alternatively the columns can use other non-reserved words.

**Comment by pi0** [comment]
Thanks for report.
