### ISSUE TITLE
`capabilities` in drivers

### ISSUE THREAD

**Issue by 43081j** [unjs/unstorage#549]
context: #539

### Describe the feature

Just opening this to track how we end up implementing `capabilities` in drivers 

We need this so we can expose what a driver supports. For example, if a driver natively supports `maxDepth` when listing keys, we can avoid running the generic algorithm/filter 

Open questions: 

- currently, we conditionally enable some things based on presence of a method (e.g. raw methods). Do we want to continue with that, or introduce a capability? Where do we draw the line?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I think we can start with `maxDepth`. I plan to deprecate `raw` methods in next major and merge with main ones (which then it makes sense to add it as capabilities)

**Comment by 43081j** [comment]
Do you have any ideas of flags we would want to expose which are not capabilities? 

I think flags makes sense as long as it's likely we'd use it for something beyond capabilities

I'll put together a branch for a first cut too 👍

**Comment by pi0** [comment]
One other example on top of my mind is `public` (some drivers including current, vercel blobs have it). But the point is there are unknown cases which later might be harder to rename or make multiple fields from drivers.

**Comment by cjpearson** [comment]
Would `ttl` also make sense as a capability? My use-case is a session implementation backed by unstorage which depends on the storage driver implementing ttl handling. It would be nice to be able to throw a warning if ttl support is missing.

**Comment by pi0** [comment]
Nice idea for `ttl 👍🏼 (we should do warning in next major however IMO and only in dev)
