### ISSUE TITLE
Cannot find module unstorage/drivers/localstorage

### ISSUE THREAD

**Issue by Hebilicious** [unjs/unstorage#56]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/13395944/169276514-ce85b5fa-cedd-4a01-96ab-953c9c3082f8.png">

Using nuxt3-rc3, pnpm (shamefully hoist), I'm getting this typescript error when trying to import the driver. The import works fine in dev, but in the built .output, it errors out.
I worked around the issue by manually pasting the source in my source files and calling defineDriver myself, but I don't know why it's happening.

**Comment by suienzan** [comment]
It's a new feature in TypeScript 4.7

Confirm you are using `typescript@4.7`. In your `tsconfig.json`, change `moduleResolution` to `Node16` or `NodeNext` to make it work.

But this will breaks modules not support it yet (many packages need update microsoft/TypeScript#48845).

I advise you change nothing from your original code, just

```ts
import localStorageDriver from "unstorage/dist/drivers/localstorage";
```

at the moment.

**Comment by pi0** [comment]
Please ping to reopen if issue still not solved in latest version.
