### ISSUE TITLE
Fs driver cannot read files with a column in their name

### ISSUE THREAD

**Issue by invernizzi** [unjs/unstorage#58]
Hello,
I've noticed that the `fsDriver` is unable to read files containing `:` (which is a valid character for filenames, at least in linux/mac).

# Steps to reproduce:
Create a directory `basedir` containing a file `a:b.txt`.
```
mkdir basedir
touch basedir/a:b.txt
```
Create the storage as usual
```
const storage = createStorage({driver: fsDriver({base: 'basedir/'}) })
```
List the keys, which works correctly (finds a key named `a:b.txt`)
```
const keys = storage.getKeys()
```
Check if the key exists, which returns `false` (instead of `true`)
```
storage.hasItem(keys[0])
```
Get the key content, which also fails.
```
storage.getItem(keys[0])
```

The culprit is this [line](https://github.com/unjs/unstorage/blob/0da9595cf04bd6367f1b4ba04966bfc118806a07/src/drivers/fs.ts#L27). Every `:` gets automatically translated to `/` in the `fs` driver, which makes the key lookup cause a file system access at `a/b.txt`.

This could be solvable (hopefully) by either encoding the filenames when loading the keys, or allowing other characters to be used as separators.

It's also possible that I overlooked a simple solution that is already implemented :) WDYT?

**Comment by pi0** [comment]
Hi dear @invernizzi. I guess we have to improve documentation but actually, this is a known limitation set by unstorage to limit common KV separators as splitters. 

If possible would be best if you can avoid using colons in storage filenames but we can surely find a way to escape (`a::b.txt`) or encode (`a%3Ab.txt`) names.

**Comment by pi0** [comment]
Closing as there is a workaround available.
