### ISSUE TITLE
Adding `cloudflare-kv` preset

### ISSUE THREAD

**Issue by Atinux** [unjs/unstorage#67]
It would be a great DX improvement to be able to have a `cloudflare-kv` preset that could use the `kv-bindings` + and `kv-http` options to offer a dev experience using the CF KV storage.

Also, if the http options are not provided, we could also fallback to `memory` storage.

**Comment by Atinux** [comment]
Also an interesting read to detect the env for the new CF worker format: https://github.com/nuxt/framework/discussions/5487#discussioncomment-3024122

**Comment by pi0** [comment]
It would be simply possible but mounting different drivers for dev and prod at same path. If not mounted, memory is used and fs can be used as well. Joining drivers adds additional logic when not needed. We might intoroduce smarter swotch in nitro level to switch from http to binding only for worker preset.
