### ISSUE TITLE
none (localstorage and fs) of the drivers are working in nuxt3

### ISSUE THREAD

**Issue by klauskobald** [unjs/unstorage#76]
<pre><script setup>
import { createStorage } from 'unstorage'
import localStorageDriver from 'unstorage/drivers/localstorage'

const storage = createStorage({
  driver: localStorageDriver({ base: 'app:' })
})
</script>
</pre>

Produces this error:

<pre>
[h3] [unhandled] H3Error: localStorage not available
    at createError (file:///Users/klausk/dev/sfinx-it-timetrack/node_modules/h3/dist/index.mjs:191:15)
    at Server.nodeHandler (file:///Users/klausk/dev/sfinx-it-timetrack/node_modules/h3/dist/index.mjs:381:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] localStorage not available
  at createError (./node_modules/h3/dist/index.mjs:191:15)  
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:381:21)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

</pre>

**Comment by ciaran-io** [comment]
Hi, I believe the issue is think the issue is because the function is called on the server side and not the client.
Either set the ssr option to false in nuxt.config or call the function with the onMounted hook.


```js
 onMounted(() => {
 const storage = createStorage({
   driver: localStorageDriver({ base: 'app:' })
})

```

**Comment by klauskobald** [comment]
yes. I was not aware that all code runs everywhere.
I started all over with my test project and did a lot differently like using use* (... the composables).

**Comment by pi0** [comment]
`localstorage` driver should be only mounted in browser environments which they support it. You can use a universal composable but mount it differently (for nuxt, you can use two plugins `plugins/storage.server.ts` and `plugins/storage.client.ts` providing `$storage`)
