### ISSUE TITLE
[server] Support POST and PATCH too for adding items

### ISSUE THREAD

**Issue by manniL** [unjs/unstorage#85]
Usually, `PUT` and `PATCH` are used interchangeably (e.g. in Laravel). So it'd be nice to add them as request options. As there is no "edit" item, I was in belief that `POST` should work for setting an item.

I'd propose to add `POST` and `PATCH` support too.

Happy to send in a PR.

**Comment by pi0** [comment]
Although it is unlikely, we might use POST and PATCH in the future for specific partial operations. Other than preference is there any reason to support new methods?

(I think similarly S3 API does not support post as i recall and only supports post for browser upload purpose)

**Comment by manniL** [comment]
Preferences as in - APIs use it similar. But I am happy with alining e.g. S3 because it is more in the domain ☺️
