### ISSUE TITLE
Synced overlay driver

### ISSUE THREAD

**Issue by zanfee** [unjs/unstorage#88]
### Describe the feature

I want to cache FS storage to improve the performance by reducing the amount of disk reads. As far as I know, there is currently no way to do this without additional code. https://github.com/unjs/unstorage/issues/15 already addresses this problem, however my idea is not only focused on caching but more generic.

My approach is to first look for a key in the memory driver, and if it's not found, look in the FS. The driver 'overlay' almost provides this functionality. It accepts an array of drivers and reads them one by one. However, data is only written to the first driver. That is, if I pass [memory, fs], the data is written to memory, but not permanently stored in the FS.

I suggest making a copy of the overlay driver and changing the functions getItem() and removeItem() so that the data is written to all drivers. Adding an option to configure whether to write only to the first or all drivers might be a good alternative. Maybe even an option to configure it per driver, but I suspect this would require additional checks and reduce performance somewhat.

```typescript
async setItem(key, value) {
  Promise.all(layers.map(layer => layer.setItem?.(key, value)))
},
async removeItem(key) {
  Promise.all(layers.map(layer => layer.setItem?.(key, OVERLAY_REMOVED)))
},
```

Apart from caching this driver could be used to sync data between multiple storage drivers.

I haven't tested the performance or usability of this approach yet.
What are your thoughts on this / alternative approaches?

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
@zanfee thanks for the suggestion, let's track in #15
